### ISSUE TITLE
switch to homebrew for xhyve

### ISSUE THREAD

**Issue by nlf** [nlf/dhyve#18]
i know we discussed this at some point and said no because the xhyve binary is out of date, but i just noticed that a `HEAD` target is available in homebrew which builds the latest git revision. that would certainly work for our purposes.

**Comment by ailispaw** [comment]
:+1:

**Comment by ailispaw** [comment]
xhyve v0.2.0 has been released.
https://github.com/mist64/xhyve/releases/tag/v0.2.0

**Comment by dch** [comment]
+1 just use brew, less submodules. given how small dhyve is, perhaps it could go direct into xhyve? the proliferation of docker-helpers is .... confusing ... atm.
