### ISSUE TITLE
create a launchd agent

### ISSUE THREAD

**Issue by nlf** [nlf/dhyve#19]
we could make a launchd agent to automatically start docker at boot (and socat if we decide to go that route)

**Comment by ailispaw** [comment]
This might be helpful for it.
https://github.com/ailispaw/boot2docker-xhyve/wiki/Running-boot2docker-xhyve-on-boot
https://gist.github.com/ailispaw/7c95167b6261f1c7aa22

**Comment by nlf** [comment]
i think launchd doesn't really line up with the goals of dhyve, i created https://github.com/nlf/dlite though which is a much more lightweight solution that does use launchd but targets only running one vm and with less flexibility
