### ISSUE TITLE
move all the various vm files into a single file

### ISSUE THREAD

**Issue by nlf** [nlf/dhyve#20]
everything but the kernel, initrd, and disk should be stored in one file. having all these text files with one line in them is silly.

**Comment by ailispaw** [comment]
FYI: I had to remove `~/.dhyve` right after updating dhyve, because there is not a config file yet.

**Comment by nlf** [comment]
yeah if you updated from master that's expected. master is a 2.0.0 work in progress and has a bunch of breaking changes.

**Comment by nlf** [comment]
btw i created a gitter chat room for this, if you can you might join there and it'll be easier for us to discuss things https://gitter.im/nlf/dhyve
