### ISSUE TITLE
bzImage download failed during first setup

### ISSUE THREAD

**Issue by marcbachmann** [nlf/dhyve#36]
I had to manually pull it.

**Comment by nlf** [comment]
did you get an error? or did it just continue and the file didn't exist?

**Comment by marcbachmann** [comment]
Yes, I've got an error. But a somewhat cryptic one. I don't have it anymore. sorry
It might have been a network problem. Currently the internet at work is not really stable.

**Comment by nlf** [comment]
Ok, that’s fine. It still at least tells me I need to add better error handling and messages to the download function.

**Comment by marcbachmann** [comment]
Just experienced this error again.
I've hardcoded the versions in the download urls and tried a `dhyve init`.
Init worked but `dhyve up` just logs those dots and I can't cancel it. I had to kill the process.
When I had a look at ~/.dhyve before killing the process, I saw that the bzImage file was missing.

```
$ dhyve init
[dhyve] saving options..done
[dhyve] generating a new ssh key..done
[dhyve] generating a disk image...done
[dhyve] downloading vm version v1.3.0..done
[dhyve] finished creating vm, to start it run 'dhyve up'
$ dhyve up
[dhyve] this command requires root, restarting with sudo..
[dhyve] starting../usr/local/bin/dhyve: line 293: 89529 Abort trap: 6           nohup xhyve $args,"$kargs" < /dev/null > "$HOME/.dhyve/vm.log" 2>&1
................................................................................^C...................................................................................[1]    89505 terminated  dhyve up
```

Those files were present in ~/.dhyve:

```
$ ll .dhyve
total 18874400
-rw-r--r--  1 marcbachmann  staff   9.0G Sep  4 18:44 disk.img
-rw-------  1 marcbachmann  staff   1.6K Sep  4 18:44 key
-rw-r--r--  1 marcbachmann  staff   418B Sep  4 18:44 key.pub
-rw-r--r--  1 marcbachmann  staff   387B Sep  4 18:44 vm.cfg
```
