### ISSUE TITLE
docker is limited to 3GB memory

### ISSUE THREAD

**Issue by marcbachmann** [nlf/dhyve#43]
I used the `-m` option when I created the container, and `dhyve status` also shows that I configured `8G` of memory. Despite that the dhyve os only shows 3GB when I use `free` to show the total memory.

**Comment by nlf** [comment]
this is actually a limitation in [xhyve](https://github.com/mist64/xhyve). once they support over 3gb of memory there, it'll start working correctly here as well

**Comment by marcbachmann** [comment]
It's supported with the most recent commit  https://github.com/mist64/xhyve/commit/793d17ccffa9a1f74f6f1a4997e73cb2e1496296
